### ISSUE TITLE
licensing?

### ISSUE THREAD

**Issue by markvdb** [andrewhodel/millcrum#10]
Hello Andrew,

Thank you so much for creating this software! Would you consider adding a clear licensing statement to it? That would make it clear if (parts of?) millcrum can be included with or adapted to the lasersaur webapp or similar FOSS software.  

Kind regards,

Mark

**Comment by andrewhodel** [comment]
I think I'll just leave it on a case by case basis with what I have written in the About page.
I'm not too hard to get ahold of if someone wants to talk about using parts of it.
