### ISSUE TITLE
The problem with fonts in a text editor

### ISSUE THREAD

**Issue by pOmelchenko** [andrewhodel/millcrum#11]
My eyes! What is wrong with this console?

<img width="1125" alt="2015-09-30 10 15 28" src="https://cloud.githubusercontent.com/assets/3578284/10186795/7e191d46-675c-11e5-9f1a-970210be1338.png">

Mac OS X Yosemite 10.10.5 - safari 8.0.8

**Comment by zrichmond** [comment]
Fine for me on Mac OS X Yosemite 10.10.5 - safari 8.0.8 and chrome.

**Comment by andrewhodel** [comment]
This was fixed here - https://github.com/andrewhodel/millcrum/commit/1c6b0cfe1ccf4a70920ec6913b9f3a8fc4494f60
