### ISSUE TITLE
Multiple cut()s with different 'tools' or move feedrate from cut to some other param

### ISSUE THREAD

**Issue by ghost** [andrewhodel/millcrum#14]
In integrating millcrum into Laserweb, one of the wants is to be able to adjust feed/speed/laserpower per 'path/layer/color" 

borrowing screenshot from from Lasaurapp to illustrate the concept
![lasaurapp](https://cloud.githubusercontent.com/assets/7695323/12002391/67ea210e-ab05-11e5-8163-c5d881694b83.png)

I made some headway on it: https://github.com/openhardwarecoza/LaserWeb/commit/958a728d46f3a35fccfb1849c53e5556ce74d835 and https://github.com/openhardwarecoza/LaserWeb/commit/e4ff991e3ea8bf4ec19507a38c4a875ba26e2411

However! Then I realised that the feed/speed etc is set per tool in mc.js, not per path.  

For the power (G1 Sxxx) param, it would also be good to set that per path/layer/something

At the end of the day, something like this:

![screenshot from 2015-12-25 12-38-24](https://cloud.githubusercontent.com/assets/7695323/12002348/7016e160-ab04-11e5-9096-2012309cf157.png)

What is your thoughts on adding support for multiple tools? (would benefit the milling and laser toolchains equally) - which I think is better approach than changing mc.cut() to require each polygon to have a feedrate, power, etc

Something like:
var tool1 = {units:"mm",diameter:0.1,passDepth:'+$('#perpass').val()+',step:1,rapid:'+$('#rapidSpeed').val()+',plunge:10000,cut:'+$('#cutSpeedLaser1').val()+',zClearance:0,returnHome:true};\n\n'; 

var tool2 = {units:"mm",diameter:0.1,passDepth:'+$('#perpass').val()+',step:1,rapid:'+$('#rapidSpeed').val()+',plunge:10000,cut:'+$('#cutSpeedLayer2').val()+',zClearance:0,returnHome:true};\n\n'; 

var polyline0 = {type:'polygon',name:'laserweb',tool:'tool1',points:[[-4.22994972382185e-14,60],[18.5402455661664,60],[18.5402455661664,14.774897680764],

var polyline1 = {type:'polygon',name:'laserweb',tool:'tool2',points:[[-4.22994972382185e-14,60],[18.5402455661664,60],[18.5402455661664,14.774897680764],

(example above I didnt mock up the laser power but you get the idea

**Comment by ghost** [comment]
Ok, I started working on the improved importer UI, for now DXF only:

https://github.com/openhardwarecoza/LaserWeb/commit/e4ff991e3ea8bf4ec19507a38c4a875ba26e2411
https://github.com/openhardwarecoza/LaserWeb/commit/76df0b5f6cbe6b1f13e8be64cb93b2261a9f8ec2
and
https://github.com/openhardwarecoza/LaserWeb/commit/5762e95d1aad20cbf0746be4bbfaaf93eada37c5

![screenshot from 2015-12-25 15-03-12](https://cloud.githubusercontent.com/assets/7695323/12003009/ac38da5e-ab18-11e5-82b3-9b0a45106355.png)

Its fully functional, by the way

But that UI needs a cleanup! Drastically (currently that's the worst looking part of LaserWeb (; hehe)

And my hack of mc.js might be questionable - cross referenced to andrewhodel/millcrum#14 ^^^

**Comment by andrewhodel** [comment]
What if you want to cut the same polygon twice with two different power values?

I am constantly writing loops that replicate a polygon multiple times.  That's why millcrum is code driven.

It sounds like what you want is a dxf tool not Millcrum. Millcrum doesn't use a concept of layers.

I don't understand the purpose of the colors, what is the real benefit to the actual work being done? If you are just using them as ids then why not just define what you need? If you are using them for groups which share certain characteristics then why not just use a variable?
