### ISSUE TITLE
SVG scaling

### ISSUE THREAD

**Issue by ghost** [andrewhodel/millcrum#15]
Inskape: 
New document, default unit and document unit = mm
Draw few squares
Do object to path
Save

millcrum.com, import svg

Console.log on millcrum.com:
all paths Array [ Array[4], Array[4], Array[4] ] init.js:238:4
svg units mm init.js:239:4
surface size: 600,400
(does detect is as mm)

However the drawn millcrum is scaled much larger that it was drawn
![millcrum](https://cloud.githubusercontent.com/assets/7695323/12003780/4ace22ba-ab36-11e5-8e58-5d7f5bd54af7.png)

![inkscape](https://cloud.githubusercontent.com/assets/7695323/12003781/4e83f510-ab36-11e5-989d-f01351127822.png)

[drawing.svg.zip](https://github.com/andrewhodel/millcrum/files/72220/drawing.svg.zip)

**Comment by andrewhodel** [comment]
Please paste the SVG as a .txt file

drawing.svg.txt

**Comment by openhardwarecoza** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>


<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="600mm"
   height="400mm"
   viewBox="0 0 2125.9843 1417.3228"
   id="svg2"
   version="1.1"
   inkscape:version="0.91 r13725"
   sodipodi:docname="drawing.svg">
  <defs
     id="defs4" />
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.35"
     inkscape:cx="394.26768"
     inkscape:cy="385.96938"
     inkscape:document-units="mm"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1855"
     inkscape:window-height="1056"
     inkscape:window-x="65"
     inkscape:window-y="24"
     inkscape:window-maximized="1" />
  <metadata
     id="metadata7">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1"
     transform="translate(0,364.96067)">
    <path
       style="fill:#0000ff;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="m 117.14286,-190.49506 428.57144,0 0,388.57145 -428.57144,0 z"
       id="rect3336" />
    <path
       style="fill:#0000ff;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="m 408.57144,298.07639 402.85715,0 0,337.14285 -402.85715,0 z"
       id="rect3338" />
    <path
       style="fill:#0000ff;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="m 620,-64.780769 457.1429,0 0,399.999999 -457.1429,0 z"
       id="rect3340" />
  </g>
</svg>

**Comment by ghost** [comment]
[drawing.txt](https://github.com/andrewhodel/millcrum/files/72447/drawing.txt)

**Comment by andrewhodel** [comment]
There is no scaling information in that file.

**Comment by openhardwarecoza** [comment]
Correct.   But look at the screenshots    rect about 125mm long (ruler at top of inkscape screenshot for reference)  comes out around 425mm long (millcrum screenshot shows millcrum scale for reference)  -   since its not a mm vs Inch or px,  i.e scaling in the file,  it does look like a bug in svg.js?

**Comment by ghost** [comment]
Ok, I did a more in depth analysis of the issue:
1.  Opened inscape and drew a 100x100mm square:

![100x100mm](https://cloud.githubusercontent.com/assets/7695323/12006954/6d32f93c-abf6-11e5-9812-8079c5331a0c.png)
1.  convert to path and save, view SVG as text:
   ![view svg as text size is in pixels](https://cloud.githubusercontent.com/assets/7695323/12006955/7a082916-abf6-11e5-9200-87cb5608fe37.png)
   
   -- What I notice is that its a m type path object with 354.33... in there  ( caught my eye because I saw it earlier)
2. Run it though svg.js 

r.readAsText(osvg.files[0]);
svg = new Svg();
svg.process(r.result);
console.log('\n\nall paths',svg.paths);
console.log('svg units '+svg.units);
1.  console log gives me:
   ![units mm but 354](https://cloud.githubusercontent.com/assets/7695323/12006976/03e4d3fa-abf7-11e5-9a0a-ea1566b5f6c1.png)

Aha, I recall seeing that 354 somewhere... Oh right, in the text view of the svg...

Since SVG saves as pixels, we should be doing (and now i recall this conversation from the early days of Lasaurapp) 

DPI (90dpi for inkscape, 72dpi for illustrator) 
Unit (mm/inch/px)
Path values should always be pixel, so pixel / dpi = inch
lets test

354.(ignoring the decimals) / 90 = 3.9333` inch (90 dots per inch)
3.9333 \* 2.54 = 9.99066666mm   (I ignored the decimals remember, but yip that should have been my 100mm square.

So, bug in svg.js in that is assumes the values in the path is in the unit detected in the header
Thats not the case, SVG is always in pixels (which is my frustration you've read me vent hundreds of times on SVG related topics, that a pixel isnt a standard unit of measure... grrr. So you always need that DPI in the calculation.  And therefore the DPI NB NB has to be a attribute passed to svg.js as well (since it could be 90 (inkscape), could be 72(illustrator), could be custom (each of these allow for custom values to prepare files for print)

**Comment by ghost** [comment]
https://github.com/stefanix/LasaurApp/blob/master/notes.md#inkscape-units and http://www.w3.org/TR/SVG/coords.html#Units

When a coordinate or length value is a number without a unit identifier (e.g., "25"), then the given coordinate or length is assumed to be in user units (i.e., a value in the current user coordinate system). For example:

<text font-size="50">Text size is 50 user units</text>

Alternatively, a coordinate or length value can be expressed as a number followed by a unit identifier (e.g., "25cm" or "15em").

By default Inkscape exports without a unit identifier, for example:

<path
       style="fill:none;stroke:#000000"
       d="m 0.5,697.53141 354.33072,0 0,354.33069 -354.33072,0 z"
       id="rect3893"
       inkscape:connector-curvature="0" />

**Comment by ghost** [comment]
If I process a drawing in px all the way, console log still shows 'svg units mm'

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="2125.9841"
   height="1417.3229"
   viewBox="0 0 2125.9843 1417.3228"
   id="svg3885"
   version="1.1"
   inkscape:version="0.91 r13725"
   sodipodi:docname="100x100mmsquare.svg">
  <defs
     id="defs3887" />
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.98994949"
     inkscape:cx="355.77795"
     inkscape:cy="21.639466"
     inkscape:document-units="px"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1855"
     inkscape:window-height="1056"
     inkscape:window-x="65"
     inkscape:window-y="24"
     inkscape:window-maximized="1"
     units="px" />
  <metadata
     id="metadata3890">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1"
     transform="translate(0,364.96067)">
    <path
       style="fill:none;stroke:#000000"
       d="M 338.40111,863.96863 A 137.38075,135.86552 0 0 1 201.02036,999.83415 137.38075,135.86552 0 0 1 63.639603,863.96863 137.38075,135.86552 0 0 1 201.02036,728.1031 137.38075,135.86552 0 0 1 338.40111,863.96863 Z"
       id="path3939" />
  </g>
</svg>
```

Ellipse - converted to path... all in px.

Also, doesnt actually import as an 'ellipse'.  Inkscape on left, millcrum on right

![side by side](https://cloud.githubusercontent.com/assets/7695323/12007706/a639b3b0-ac19-11e5-90ea-f6ec68ce5517.png)

**Comment by andrewhodel** [comment]
That's unfortunate that they don't follow the SVG standard, I think
I'll stick with that but it should be easy to divide by whatever unit
you want.

Some people do write svg by hand (for the curve control).
