### ISSUE TITLE
Problem with cut('pocket') on a rectangle with rounded corners

### ISSUE THREAD

**Issue by SebKuzminsky** [andrewhodel/millcrum#5]
Playing with the demo at millcrum.com, the following input produces an obviously wrong tool path:

var tool = {units:'mm',diameter:6.35,passDepth:4,step:1,rapid:2000,plunge:100,cut:600,zClearance:5,returnHome:true};
var mc = new Millcrum(tool);
mc.surface(100,100);
var rectCornerRadius = {type:'rect',xLen:80,yLen:80,cornerRadius:4};
mc.cut('pocket', rectCornerRadius, 4, [0,0]);
mc.get();

**Comment by SebKuzminsky** [comment]
If i take out the ",cornerRadius:4" from the rectangle definition, it generates the expected tool path.

**Comment by andrewhodel** [comment]
Very likely the same issue as issue #4 
Once that's fixed I'll try this out again.

**Comment by tbfleming** [comment]
Here's where it gets interesting:

![image](https://cloud.githubusercontent.com/assets/418464/8339345/bf35ad14-1a84-11e5-967b-209a4d125c4a.png)

The 2nd offset operation produces a polygon with a region that has a negative winding. Clipper removes areas with negative windings after allowing them to happen. There's a proof that removing these areas produces correct results.

**Comment by andrewhodel** [comment]
@tbfleming I figured out that messed up X clipping issue.
